AllCops:
  TargetRubyVersion: ~
  TargetRailsVersion: 5.2
  Exclude:
    - '**/bin/**/*'
    - '**/db/**/*'
    - '**/in_progress/**/*'
    - '**/tmp/**/*'
    - '**/script/setup'
    - '**/lib/tasks/**/*'
    - '**/vendor/**/*'
    - 'config/initializers/patches/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 40

Style/LambdaCall:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - '**/spec/**/*'

Style/NegatedIf:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/GuardClause:
  Enabled: false