# Add configuration values here, as shown below.
#
# DON'T PUT SENSITIVE DATA IN HERE!!!!!

SECONDS_PER_GAME_HOUR: "1"

development:
  LASTFM_API_KEY: 7c66615ca5d9177b5489615b29377752
production:
  SECONDS_PER_GAME_HOUR: "60"
