development:
  :concurrency: 5
production:
  :concurrency: 5
:queues:
  - default

:dynamic: true
#:dynamic_every: <if dynamic is true, the schedule is reloaded every interval [5s by default]>
#:enabled: <enables scheduler if true [true by default]>
#:scheduler:
#  :listened_queues_only: <push jobs whose queue is being listened by sidekiq [false by default]>

:schedule:
  DailyRunningFinancialWorker:
    cron: '0 20 * * *'   # Runs every day at 8pm
