:dynamic: true
#:dynamic_every: <if dynamic is true, the schedule is reloaded every interval [5s by default]>
#:enabled: <enables scheduler if true [true by default]>
#:scheduler:
#  :listened_queues_only: <push jobs whose queue is being listened by sidekiq [false by default]>

:schedule:
  DailyRunningFinancial:
    cron: '0 20 * * *'   # Runs every day at 8pm
